name: Build & push clang-format image
on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write        # allow GITHUB_TOKEN to push

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3      # multi-arch builder
      - uses: docker/login-action@v3             # log in with GITHUB_TOKEN
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          #  ↓↓↓  repo-scoped tags  ↓↓↓
          tags: |
            ghcr.io/azimafroozeh/clang-format-python/clang-format-python:14
            ghcr.io/azimafroozeh/clang-format-python/clang-format-python:latest
