name: Build & push clang-format image

on:
  push:
    branches: [main]

permissions:
  packages: write        # allow this workflow’s GITHUB_TOKEN to push
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Buildx with QEMU so we can build amd64 + arm64
      - uses: docker/setup-buildx-action@v3

      # Log in to GHCR with the workflow’s GITHUB_TOKEN
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push the image
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile          # your Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/azimafroozeh/clang-format-python/clang-format-python:14
            ghcr.io/azimafroozeh/clang-format-python/clang-format-python:latest
